(TeX-add-style-hook "Python_RPi_Part_1"
 (lambda ()
    (TeX-run-style-hooks
     "beamerthemesplit"
     "natbib"
     "authoryear"
     "numbers"
     "sort"
     "square"
     "times"
     "alltt"
     "hyperref"
     "relsize"
     "amsmath"
     "inputenc"
     "utf8"
     "babel"
     "spanish"
     "color"
     "graphicx"
     ""
     "latex2e"
     "beamer10"
     "beamer"
     "10pt"
     "colorlinks"
     "format"
     "header")))

